
```{r}
path <- "data"
setwd(path)

# Practice data
training_data <- data.frame(
    pid = c(0, 1, 2, 3, 4, 5),
    training = c(13.2, 14.4, 13.8, 14.1, 15.7, 16.1)
)

load_files <- function(file_pattern, create_correct_column = TRUE) {
    # find matching files
    df_files <- list.files(".", file_pattern)
    # combine into single dataframe
    df <- dplyr::bind_rows(lapply(df_files, read.csv))
    df <- subset(df, select=-c(timestamp, facilitator, event, item))

    # remove non-data rows
    df <- dplyr::filter(df, stimulus != "")

    if(create_correct_column){
        df$correct <- as.integer(df$stimulus == df$selection)
    }

    # configure data types
    ordered_conditions <- c("Pre-test", "Post-test")
    df <- within(df, {
        pid <- as.factor(pid)
        condition <- factor(
            condition,
            levels = ordered_conditions,
            labels = ordered_conditions
        )
        selection <- as.factor(selection)
        stimulus <- as.factor(stimulus)
    })

    df <- merge(df, training_data, key = "pid")

    df$training <- ifelse(df$condition == "Pre-test", 0, df$training)

    return(df)
}

bin_lme <- function(formula, data) {
    data <- rlang::enexpr(data)
    model_call <- rlang::expr(lme4::glmer(
        formula = formula,
        data = !!data,
        family = binomial,
        control = lme4::glmerControl(optimizer = "bobyqa")
    ))

    model <- eval(model_call)
    print(summary(model))

    return(model)

#    model <- lme4::glmer(
#        formula = formula,
#        data = data,
#        family = binomial,
#        control = lme4::glmerControl(optimizer = "bobyqa")
#    )
#    print(summary(model))
#    return(model)
}
```

# Phonemes
## Load data
```{r}
phoneDF <- load_files("_phonemes_")
phoneDF <- within(phoneDF, {
    phoneType <- as.factor(ifelse(substring(stimulus, 1, 1) == "a", "Consonant", "Vowel"))
    speakerGender <- as.factor(toupper(substring(stimfile, 1, 1)))
    stimfile <- as.factor(stimfile)
})

# Check ratios
summary(phoneDF$correct)
table(phoneDF$pid, phoneDF$correct)
table(phoneDF$phoneType, phoneDF$correct)
table(phoneDF$condition, phoneDF$correct)

```

## Explore and visualize
```{r}

phoneSummary <- dplyr::summarise(
    dplyr::group_by(phoneDF, pid, training, phoneType),
    correctPortion = 100*mean(correct),
    se = 100*sd(correct)/sqrt(length(correct))
)

# Adds a line for consonants+vowels collapsed together
#phoneSummary2 <- dplyr::summarise(
#    dplyr::group_by(phoneDF, pid, training),
#    correctPortion = 100*mean(correct),
#    se = 100*sd(correct)/sqrt(length(correct))
#)
#phoneSummary2$phoneType <- "Combined"
#phoneSummary <- dplyr::union_all(phoneSummary, phoneSummary2)


ggplot2::ggplot(phoneSummary, ggplot2::aes(x = training, y = correctPortion, shape = phoneType, group = phoneType, color = phoneType)) +
    ggplot2::facet_wrap(facets = ggplot2::vars(pid)) +
    ggplot2::geom_line() +
    ggplot2::geom_point(size = 3) +
    ggplot2::geom_errorbar(
        ggplot2::aes(ymin=correctPortion-se, ymax=correctPortion+se),
        width=1,
        position=ggplot2::position_dodge(2)
    ) +
    ggplot2::ylim(0, 100) +
    ggplot2::labs(
        colour = "Phone Type",
        shape = "Phone Type",
        x = "Training Time (Hours)",
        y = "Percentage Correct",
        title = "Phoneme Recognition (by participant)"
    )

ggplot2::ggsave(plot=ggplot2::last_plot(), file="../plots/phoneme-recognition.png")

# this was an attempt to plot all the people on a single graph, but still separate lines
#ggplot2::ggplot(phoneSummary, ggplot2::aes(x = training, y = 100*correctPortion, shape = phoneType, group = phoneType, color = phoneType)) +
#    ggplot2::geom_point(size = 3) +
#    ggplot2::ylim(0, 100) +
#    ggplot2::geom_smooth(method=lm) +
#    ggplot2::labs(
#        colour = "Phone Type",
#        shape = "Phone Type",
#        x = "Time",
#        y = "Correct %"
#    )
#
```

## Model
```{r}
phone_model <- function(formula) bin_lme(formula = formula, data = phoneDF)

phone_m0 <- phone_model(correct ~ 1 + (training|pid))
phone_m1 <- phone_model(correct ~ training + (training|pid))
phone_m2 <- phone_model(correct ~ training + phoneType + (training|pid))
phone_m3 <- phone_model(correct ~ training*phoneType + (training|pid))

#plot(ggeffects::ggeffect(phone_m1, terms = c("training [0:50]"), type="re"))
#plot(ggeffects::ggeffect(phone_m2, terms = c("training [0:50]", "phoneType"), type="re"))
#plot(ggeffects::ggeffect(phone_m3, terms = c("training [0:50]", "phoneType"), type="re"))

anova(phone_m0, phone_m1, phone_m2, phone_m3)

```

# Prosody
## Load Data
```{r}
prosodyDF <- load_files("_prosody_")
prosodyDF <- tidyr::separate(data = prosodyDF, col = stimfile, into = "sentenceID", sep = "_", extra = "drop", remove = FALSE)
prosodyDF$prosodyType <- as.factor(ifelse(substring(prosodyDF$stimfile, 1, 1) == "f", "Focus", "Phrase"))

focusDF <- dplyr::filter(prosodyDF, prosodyDF$prosodyType == "Focus")
focusDF$stimfile <- as.factor(focusDF$stimfile)
focusDF$sentenceID <- as.factor(focusDF$sentenceID)

phraseDF <- dplyr::filter(prosodyDF, prosodyDF$prosodyType == "Phrase")
phraseDF$stimfile <- as.factor(phraseDF$stimfile)
phraseDF$sentenceID <- as.factor(phraseDF$sentenceID)

prosodySummary <- dplyr::summarise(
    dplyr::group_by(prosodyDF, pid, prosodyType, training),
    correctPortion = 100*mean(correct),
    se = 100*sd(correct)/sqrt(length(correct))
)

ggplot2::ggplot(prosodySummary, ggplot2::aes(x = training, y = correctPortion, shape = prosodyType, group = prosodyType, color = prosodyType)) +
    ggplot2::facet_wrap(facets = ggplot2::vars(pid)) +
    ggplot2::geom_line() +
    ggplot2::geom_point(size=4) +
    ggplot2::geom_errorbar(
        ggplot2::aes(ymin=correctPortion-se, ymax=correctPortion+se),
        width=1,
        position=ggplot2::position_dodge(2)
    ) +
    ggplot2::ylim(0, 100) +
    ggplot2::labs(
        colour = "Feature",
        shape = "Feature",
        x = "Training Time (hours)",
        y = "Percentage Correct",
        title = "Prosody Perception (by participant)"
    )

ggplot2::ggsave(plot=ggplot2::last_plot(), file="../plots/prosody-perception.png")
```
## Focus - Model & Test
```{r}
focus_model <- function(formula) bin_lme(formula = formula, data = focusDF)

focus_m0 = focus_model(correct ~ 1 + (training | pid))
focus_m1 = focus_model(correct ~ training + (training | pid))
focus_m2 = focus_model(correct ~ training + (training | pid) + (1 | sentenceID))

anova(focus_m0, focus_m1, focus_m2)

```

## Phrase Boundary - Model & Test
```{r}
phrase_model <- function(formula) bin_lme(formula = formula, data = phraseDF)

phrase_m0 <- phrase_model(correct ~ 1 + (training | pid))
phrase_m1 <- phrase_model(correct ~ training + (training | pid))
phrase_m2 <- phrase_model(correct ~ training + (training | pid) + (1 | sentenceID))

anova(phrase_m0, phrase_m1, phrase_m2)

```

# Perceptual Integration
## Load Data
```{r}
integrationDF <- load_files("_integration_", create_correct_column = FALSE)
integrationDF <- within(integrationDF, {
    integrated <- 1-as.integer(mapply(grepl, pattern = selection, x = stimulus))
    auditoryStim <- as.factor(substring(stimulus, 1, 2))
    tactileStim <- as.factor(substring(stimulus, 4, 5))
})

```

## Explore & Visualize
```{r}
integrationSummary <- dplyr::summarise(
    dplyr::group_by(integrationDF, pid, condition),
    correctPortion = 100*mean(integrated),
    se = 100*sd(integrated)/sqrt(length(integrated)),
    training = mean(training),
)

ggplot2::ggplot(integrationSummary, ggplot2::aes(x = training, y = correctPortion, group = 1)) +
    ggplot2::facet_wrap(facets = ggplot2::vars(pid)) +
    ggplot2::geom_line() +
    ggplot2::geom_point(size=4) +
    ggplot2::geom_errorbar(
        ggplot2::aes(ymin=correctPortion-se, ymax=correctPortion+se),
        width=1.5,
        position=ggplot2::position_dodge(2)
    ) +
    ggplot2::ylim(0, 100) +
    ggplot2::labs(
        title = "Perceptual Integration (by participant)",
        x = "Training Time (Hours)",
        y = "Percentage Integrated"
    )

ggplot2::ggsave(plot=ggplot2::last_plot(), file="../plots/integration01.png")

integrationSummaryByStim <- dplyr::summarise(dplyr::group_by(integrationDF, pid, condition, stimulus), correctPortion = mean(integrated), training = mean(training))

ggplot2::ggplot(integrationSummaryByStim, ggplot2::aes(x = training, y = 100*correctPortion, group = stimulus, color = stimulus)) +
    ggplot2::facet_wrap(facets = ggplot2::vars(pid)) +
    ggplot2::geom_line() +
    ggplot2::geom_point(size=4) +
    ggplot2::ylim(0, 100) +
    ggplot2::labs(
        title = "Perceptual Integration (by participant)",
        x = "Training Time (Hours)",
        y = "Percentage Integrated"
    )

ggplot2::ggplot(integrationSummaryByStim, ggplot2::aes(x = training, y = 100*correctPortion, shape = pid, group = pid, color = pid)) +
    ggplot2::facet_wrap(facets = ggplot2::vars(stimulus)) +
    ggplot2::geom_line() +
    ggplot2::geom_point(size=4) +
    ggplot2::ylim(0, 100) +
    ggplot2::labs(
        title = "Perceptual Integration (by stimulus)",
        x = "Training Time (Hours)",
        y = "Percentage Integrated"
    )



#integrationSummaryByStim <- dplyr::summarise(dplyr::group_by(integrationDF, stimulus, training), correctPortion = mean(integrated))
#
#ggplot2::ggplot(integrationSummaryByStim, ggplot2::aes(x = training, y = 100*correctPortion, group = 1)) +
#    ggplot2::facet_wrap(facets = ggplot2::vars(stimulus)) +
#    ggplot2::geom_line() +
#    ggplot2::geom_point(size=4) +
#    ggplot2::ylim(0, 100) +
#    ggplot2::labs(x = "Time", y = "% Integrated")
#
#integrationSummaryByStimAndPid <- dplyr::summarise(dplyr::group_by(integrationDF, stimulus, pid, training), correctPortion = mean(integrated))
#
#ggplot2::ggplot(integrationSummaryByStimAndPid, ggplot2::aes(x = training, y = 100*correctPortion, group = 1)) +
#    ggplot2::facet_grid(rows = ggplot2::vars(stimulus), cols = ggplot2::vars(pid)) +
#    ggplot2::geom_line() +
#    ggplot2::geom_point(size=4) +
#    ggplot2::ylim(0, 100) +
#    ggplot2::labs(x = "Time", y = "% Integrated")
```

## Model & Test
```{r}
integration_model <- function(formula) bin_lme(formula = formula, data = integrationDF)

integration_m0 <- integration_model(integrated ~ 1 + (training | pid))
integration_m1 <- integration_model(integrated ~ training + (training | pid))
integration_m2 <- integration_model(integrated ~ training + (training | pid) + (1 | stimulus))

anova(integration_m0, integration_m1, integration_m2)


```
